export enum NotificationType {
  NEW_PURCHASE_REQUEST = 'NEW PURCHASE REQUEST',
  MESSAGE = 'MESSAGE',
  BID_INVIATION = 'BID INVITATION',
  COMPANY_NEEDS_VERIFICATION = 'COMPANY NEEDS VERIFICATION',
  COMPANY_JOINING_REQUEST = 'COMPANY JOINING REQUEST',
  COMPANY_VERIFIED = 'COMPANY VERIFIED',
  COMPANY_NOT_VERIFIED = 'COMPANY NOT VERIFIED',
  PURCHASE_REQUEST_POSTPONED = 'PURCHASE REQUEST POSTPONED',
  DISQUALIFIED = 'DISQUALIFIED',
  NEW_BID = 'NEW BID',
  FEEDBACK = 'FEEDBACK',
  WINNING_BID = 'WINNING BID',
  BID_LOCKED = 'BID LOCKED',
  BID_bidding_deadline = 'BID DUE DATE',
  PURCHASE_REQUEST_CANCELLED = 'PURCHASE REQUEST CANCELLED',
  SUPPLIER_NEEDS_A_COMPANY = 'SUPPLIER NEEDS A COMPANY',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
}
