networks:
  taqathon-network:
    driver: bridge

volumes:
  postgres_data:

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taqathon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taqathon_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./create-db-users.sh:/docker-entrypoint-initdb.d/create-db-users.sh
    networks:
      - taqathon-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taqathon-frontend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    networks:
      - taqathon-network